EExam/EExam/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.core.urlresolvers import reverse, reverse_lazy
from EExam import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^exam/', include('exam.urls', namespace='exam')),
    url(r'^reception/', include('reception.urls', namespace='reception')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^group/(?P<num>[0-9]+)/$', 'exam.views.get_group', name="get_group"),
    url(r'^signin/$', 'exam.views.signin', name="signin"),
    url(r'^about/$', login_required(TemplateView.as_view(template_name="exam/about.html"), login_url=reverse_lazy("signin")), name="about"),
    url(r'^change-password$', 'exam.views.change_password', name="change_password"),
    url(r'^$', 'exam.views.index', name="index"),
    url(r'^signout/$', 'exam.views.signout', name='signout'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

EExam/exam/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import TemplateView

urlpatterns = patterns('exam.views',
    url(r'^(?P<num>[0-9]+)/consultation/$', 'consult', name='consultation'),
    url(r'^new$', 'new_exam', name="new"),
    url(r'^(?P<num>[0-9]+)$', 'details', name="details"),
    url(r'^(?P<num>[0-9]+)/edit$', 'edit_exam', name='edit'),
    url(r'^(?P<num>[0-9]+)/delete', 'delete_exam', name='delete'),
    url(r'^(?P<num>[0-9]+)/queue$', 'queue_by_students', name="queue_by_students"),
    url(r'^(?P<num>[0-9]+)/start$', 'start_exam', name="start_exam")
)

EExam/reception/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('reception.views',
    url(r'^(?P<exam_num>[0-9]+)/teacher$', 'index_teacher', name="teacher"),
    url(r'^(?P<exam_num>[0-9]+)/student$', 'index_student', name="student"),
    url(r'^(?P<exam_num>[0-9]+)/start$', 'start_reception', name="start"),
    url(r'^(?P<exam_num>[0-9]+)/finish$', 'finish_exam', name="finish"),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/start$', 'start_reception_for_student', name="start_student"),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/acceptance$', 'acceptance_reception_for_student', name='acceptance_student'),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/finish', 'finish_reception_for_student', name='finish_student'),
)

EExam/reception/models.py
# -*- coding: utf-8 -*-

from django.db import models
from exam.models import Exam, Student


class Reception(models.Model):
    exam = models.ForeignKey(Exam)
    start_time = models.DateTimeField(auto_now=True)
    end_time = models.DateTimeField(null=True)

    def __unicode__(self):
        return 'Reception ' + self.exam.subject.name


class ReceptionPlace(models.Model):

    STATUS_CHOICES = (
        (0, 'В очереди'),
        (1, 'Ожидают'),
        (3, 'Сдают'),
    )

    number = models.IntegerField()
    reception_time = models.DateTimeField()  # ожидаемое время приема
    student = models.ForeignKey(Student)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    evaluation = models.IntegerField(null=True)
    reception = models.ForeignKey(Reception)

    def __unicode__(self):
        return 'ReceptionPlace ' + self.student.user.first_name + ' ' + self.student.user.last_name

EExam/reception/views.py
from datetime import timedelta, datetime
import json
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from exam.models import Exam, Student, Teacher
from reception.models import Reception, ReceptionPlace


def teacher_only(v):
    def wrapper(request, *a, **k):
        user = request.user
        if Student.objects.filter(user=user).count() > 0:
            return HttpResponseRedirect(reverse("index"))
        else:
            return v(request, *a, **k)

    return wrapper


def student_only(v):
    def wrapper(request, *a, **k):
        user = request.user
        if Teacher.objects.filter(user=user).count() > 0:
            return HttpResponseRedirect(reverse("index"))
        else:
            return v(request, *a, **k)

    return wrapper


@teacher_only
def start_reception(request, exam_num):
    exam = Exam.objects.get(pk=exam_num)
    reception = Reception(
        exam=exam
    )
    reception.save()

    count = 1
    students_per_time = exam.students_per_time
    time_for_student = exam.time_for_student
    for student_pk in exam.queue.get_students():
        if students_per_time == 0:
            time_for_student += exam.time_for_student
        reception_time = reception.start_time + timedelta(minutes=time_for_student)
        student = Student.objects.get(pk=student_pk)
        reception_place = ReceptionPlace(
            number=count,
            reception_time=reception_time,
            student=student,
            status=0,
            reception=reception
        )
        reception_place.save()
        count += 1
        students_per_time -= 1

    return HttpResponseRedirect(reverse("reception:teacher", kwargs={'exam_num': exam_num}))


@teacher_only
def index_teacher(request, exam_num):
    context = {}
    exam = Exam.objects.get(pk=exam_num)
    reception = Reception.objects.get(exam=exam)
    queue = []
    for student_pk in exam.queue.get_students():
        student = Student.objects.get(pk=student_pk)
        reception_place = ReceptionPlace.objects.get(reception=reception, student=student)
        if not reception_place.end_time:
            queue.append(Student.objects.get(pk=student_pk))
    print queue
    context["queue"] = queue
    context["exam"] = exam.pk
    return render(request, "reception/teacher.html", context)


@teacher_only
def start_reception_for_student(request, exam_num, stud_num):
    exam = Exam.objects.get(pk=exam_num)
    student = Student.objects.get(pk=stud_num)
    reception = Reception.objects.get(exam=exam)
    reception_place = ReceptionPlace.objects.get(reception=reception, student=student)
    reception_place.start_time = datetime.now()
    reception_place.status = 1

    student = {
        "pk": student.pk,
        "first_name": student.user.first_name,
        "last_name": student.user.last_name,
        "group": student.group.number
    }
    data = {}
    data["student"] = student

    reception_place.save()
    return HttpResponse(json.dumps(data), content_type="application/json")


@teacher_only
def acceptance_reception_for_student(request, exam_num, stud_num):
    exam = Exam.objects.get(pk=exam_num)
    student = Student.objects.get(pk=stud_num)
    reception = Reception.objects.get(exam=exam)
    reception_place = ReceptionPlace.objects.get(reception=reception, student=student)
    reception_place.status = 3

    student = {
        "pk": student.pk,
        "first_name": student.user.first_name,
        "last_name": student.user.last_name,
        "group": student.group.number
    }
    data = {}
    data["student"] = student

    reception_place.save()
    return HttpResponse(json.dumps(data), content_type="application/json")


@teacher_only
def finish_reception_for_student(request, exam_num, stud_num):
    exam = Exam.objects.get(pk=exam_num)
    student = Student.objects.get(pk=stud_num)
    reception = Reception.objects.get(exam=exam)
    reception_place = ReceptionPlace.objects.get(reception=reception, student=student)
    reception_place.end_time = datetime.now()
    reception_place.evaluation = int(request.GET["eval"])

    reception_place.save()
    return HttpResponse(json.dumps("Ok"), content_type="application/json")


@teacher_only
def finish_exam(request, exam_num):
    exam = Exam.objects.get(pk=exam_num)
    reception = Reception.objects.get(exam=exam)
    reception.end_time = datetime.now()
    reception.save()
    return HttpResponseRedirect(reverse("exam:details", kwargs={'num': exam_num}))


@student_only
def index_student(request, exam_num):
    context = {}
    exam = Exam.objects.get(pk=exam_num)
    student = Student.objects.get(user=request.user)
    reception = Reception.objects.get(exam=exam)
    reception_place = ReceptionPlace.objects.get(reception=reception, student=student)
    context["place"] = reception_place
    return render(request, 'reception/student.html', context)

EExam/templates/reception/student.html
{% extends "base.html" %}

{% block content %}

    <div class="container">

        <div class="text-center">
            <div style="font-size: 4em">Ваш персональный номер:</div>
            <div style="font-size: 14em">{{ place.number }}</div>
            {% if place.status == place.STATUS_CHOICES["Сдают"] %}
                <div style="font-size: 2em">Проходите в кабинет</div>
            {% else %}
                <div style="font-size: 2em">Примерное время приема: {{ place.reception_time }}</div>
            {% endif %}
        </div>

    </div>

{% endblock %}

EExam/templates/reception/teacher.html
{% extends "base.html" %}

{% block content %}

    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                <span style="font-size: 20px">Сейчас у преподавателя:</span>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6 col-lg-4">
                <div id="studInfo" class="text-left">
                    Нет
                </div>
                <div id="studId" style="display: none;"></div>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-2">
                <div>
                    <label class="control-label">Оценка:</label><br>
                    <input id="evaluation" name="evaluation" type="text" class="form-control"/><br>
                    <input type="submit" class="btn btn-primary" value="Завершить" onclick="finishReception()"/>
                </div>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                <label>Ожидают</label><br>
                <select id="wait" multiple class="form-control"
                        style="height:300px;">
                    {% for student in queue %}
                        <option disabled
                                value="{{ student.pk }}">{{ student.user.last_name }} {{ student.user.first_name }}</option>
                    {% endfor %}
                </select>

            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3 text-center" style="height:300px;"><br><br><br>
                <input type="button" value=">" class="btn btn-primary btn-lg" onclick="toExam()"/>
                <br>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                <label>Сдают</label><br>
                <select id="reception" multiple class="form-control"
                        style="height:300px;">
                </select>
                <br>
                <input type="button" value="На прием" class="btn btn-primary" onclick="toReception()"/>

                <form action="{% url 'reception:finish' exam %}" METHOD="post" style='display:inline;'>
                    {% csrf_token %}
                    <input type="submit" value="Закончить прием" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
    <script>


        $('form').validate({
            rules: {
                evaluation: {
                    required: true,
                    min: 0,
                    max: 100
                }
            },
            messages: {
                evaluation: {
                    required: "Оценка не может быть пустой",
                    min: "Минимальная оценка 0",
                    max: "Максимальная оценка 100"
                }
            },

            errorClass: 'error'
        });


        function toExam() {
            var wait = document.getElementById('wait');
            var reception = document.getElementById('reception');

            if (wait.length > 0) {
                var ch = wait.children[0];
                wait.removeChild(ch);
                ch.disabled = false;
                reception.appendChild(ch);
                jQuery.ajax({
                    url: '/reception/' + {{ exam }} +'/student/' + ch.value + '/start',
                    type: "GET",
                    dataType: "json",
                    success: function (response) {
                    }
                });
            }
        }

        function toReception() {
            var reception = document.getElementById('reception');
            var studInfo = document.getElementById('studInfo');
            var studId = document.getElementById('studId');

            if (reception.length > 0) {
                var ch = reception.children[reception.selectedIndex];
                var id = ch.value;
                jQuery.ajax({
                    url: '/reception/' + {{ exam }} +'/student/' + id + '/acceptance',
                    type: "GET",
                    dataType: "json",
                    success: function (response) {
                        var student = response["student"];
                        console.log(studInfo.innerHTML);
                        if (studInfo.innerHTML.trim() == 'Нет') {
                            studInfo.innerHTML = student["first_name"] + '<br>' + student["last_name"] + '<br>' + student["group"];
                            studId.innerHTML = student["pk"];
                            reception.removeChild(ch);
                        } else {
                            alert("Закончите прием текущего студента");
                        }
                    }
                });
            }

        }


        function finishReception() {
            var studId = document.getElementById('studId');
            var studEval = document.getElementById('evaluation');
            var studInfo = document.getElementById('studInfo');
            if (studEval != "" && studId != "") {
                jQuery.ajax({
                    url: '/reception/' + {{ exam }} +'/student/' + studId.innerHTML + '/finish',
                    type: "GET",
                    data: {"eval": studEval.value},
                    dataType: "json",
                    success: function (response) {
                        studId.innerHTML = "";
                        studInfo.innerHTML = "Нет";
                        studEval.innerHTML = "";
                    }
                });
            }

        }

        function finishExam() {

        }
    </script>

{% endblock %}