EExam/EExam/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.core.urlresolvers import reverse, reverse_lazy
from EExam import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^exam/', include('exam.urls', namespace='exam')),
    url(r'^reception/', include('reception.urls', namespace='reception')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^group/(?P<num>[0-9]+)/$', 'exam.views.get_group', name="get_group"),
    url(r'^signin/$', 'exam.views.signin', name="signin"),
    url(r'^about/$', login_required(TemplateView.as_view(template_name="exam/about.html"), login_url=reverse_lazy("signin")), name="about"),
    url(r'^change-password$', 'exam.views.change_password', name="change_password"),
    url(r'^$', 'exam.views.index', name="index"),
    url(r'^signout/$', 'exam.views.signout', name='signout'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

EExam/exam/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import TemplateView

urlpatterns = patterns('exam.views',
    url(r'^(?P<num>[0-9]+)/consultation/$', 'consult', name='consultation'),
    url(r'^new$', 'new_exam', name="new"),
    url(r'^(?P<num>[0-9]+)$', 'details', name="details"),
    url(r'^(?P<num>[0-9]+)/edit$', 'edit_exam', name='edit'),
    url(r'^(?P<num>[0-9]+)/delete', 'delete_exam', name='delete'),
    url(r'^(?P<num>[0-9]+)/queue$', 'queue_by_students', name="queue_by_students"),
    url(r'^(?P<num>[0-9]+)/start$', 'start_exam', name="start_exam")
)

EExam/reception/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('reception.views',
    url(r'^(?P<exam_num>[0-9]+)/teacher$', 'index_teacher', name="teacher"),
    url(r'^(?P<exam_num>[0-9]+)/student$', 'index_student', name="student"),
    url(r'^(?P<exam_num>[0-9]+)/start$', 'start_reception', name="start"),
    url(r'^(?P<exam_num>[0-9]+)/finish$', 'finish_exam', name="finish"),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/start$', 'start_reception_for_student', name="start_student"),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/acceptance$', 'acceptance_reception_for_student', name='acceptance_student'),
    url(r'^(?P<exam_num>[0-9]+)/student/(?P<stud_num>[0-9]+)/finish', 'finish_reception_for_student', name='finish_student'),
)

EExam/exam/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
import json


class Course(models.Model):
    number = models.IntegerField()
    specialty = models.CharField(max_length=120, blank=True)

    def __unicode__(self):
        return str(self.number)


class Group(models.Model):
    number = models.CharField(max_length=10, blank=True)
    course = models.ForeignKey(Course)

    def __unicode__(self):
        return str(self.number)


class Student(models.Model):
    group = models.ForeignKey(Group)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name


class Subject(models.Model):
    name = models.CharField(max_length=120, blank=True)
    hours = models.IntegerField()

    def __unicode__(self):
        return self.name


class Teacher(models.Model):
    subject = models.ManyToManyField(Subject)
    groups = models.ManyToManyField(Group)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name

    def get_subjects(self):
        return "\n".join([s.name for s in self.subject.all()])

    def get_groups(self):
        return "\n".join([g.number for g in self.groups.all()])


class Queue(models.Model):
    by_students = models.BooleanField()
    students = models.CharField(max_length=1000)

    def set_students(self, x):
        self.students = json.dumps(x)

    def get_students(self):
        return json.loads(self.students)

    def __unicode__(self):
        return 'Очередь ' + str(self.pk)


class Consultation(models.Model):
    start_time = models.DateTimeField()
    location = models.CharField(max_length=50)

    def __unicode__(self):
        return 'Консультация ' + str(self.pk)


class Question(models.Model):
    text = models.CharField(max_length=255, blank=True)
    author = models.ForeignKey(Student)
    date = models.DateTimeField(auto_now=True)
    consultation = models.ForeignKey(Consultation)

    def __unicode__(self):
        return 'Вопрос от ' + self.author.user.first_name + ' ' + self.author.user.last_name


class Exam(models.Model):
    teacher = models.ForeignKey(Teacher)
    subject = models.ForeignKey(Subject)
    groups = models.ManyToManyField(Group)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    queue = models.ForeignKey(Queue)
    students_per_time = models.IntegerField()
    time_for_student = models.IntegerField()
    location = models.CharField(max_length=50)
    consultation = models.ForeignKey(Consultation)
    start = models.BooleanField(default=False)

    def __unicode__(self):
        return 'Экзамен по ' + self.subject.name

    def get_groups(self):
        return "\n".join([g.number for g in self.groups.all()])


class Material(models.Model):
    name = models.CharField(max_length=50, blank=True)
    file = models.FileField(upload_to="files/")
    exam = models.ForeignKey(Exam)

    def __unicode__(self):
        return self.name

EExam/exam/forms.py
# -*- coding: utf-8 -*-
from django import forms
from exam.models import Material


class SigninForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': "username", 'placeholder': 'Логин'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Пароль'}))


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_new_password = forms.CharField(widget=forms.PasswordInput)


class UploadMaterialForm(forms.Form):
    material = forms.FileField(label='Select a file', help_text='max. 42 megabytes')

    class Meta:
        model = Material

EExam/exam/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from datetime import datetime
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils import timezone
from exam.forms import SigninForm, UploadMaterialForm
from models import Exam, Question, Consultation, Subject, Group, Student, Teacher, Queue, Material
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from reception.models import Reception
from reception.views import teacher_only, student_only


def no_auth_please(v):
    def wrapper(request, *a, **k):
        user = request.user
        if user.is_authenticated():
            return HttpResponseRedirect(reverse("index"))
        else:
            return v(request, *a, **k)

    return wrapper


@login_required(login_url=reverse_lazy("signin"))
def consult(request, num):
    exam = Exam.objects.get(pk=num)

    if request.POST:
        user = request.user

        question = Question()
        question.text = request.POST.get('question_text')
        author = Student.objects.get(user=user)
        question.author = author
        question.consultation = exam.consultation

        question.save()

        return HttpResponseRedirect(reverse("exam:consultation", kwargs={'num': num}))
    else:
        context = {}
        if Teacher.objects.filter(user=request.user).count() > 0:
            context["teacher"] = True
            context["questions"] = Question.objects.filter(consultation=exam.consultation)
        context["consultation"] = exam.consultation
        context["exam"] = exam
        return render(request, 'exam/consultation.html', context)


@no_auth_please
def signin(request):
    if request.POST:
        form = SigninForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"]
            )
            if user:
                login(request, user)
                if not request.POST.get('remember_me'):
                    request.session.set_expiry(0)

                if Teacher.objects.filter(user=user).count() > 0:
                    request.session["teacher"] = True
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponseRedirect(reverse('signin'))

        context = {"form": form}
        return render(request, "exam/signin.html", context)
    else:
        form = SigninForm()
        context = {"form": form}
        return render(request, "exam/signin.html", context)


@login_required(login_url=reverse_lazy("signin"))
def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse("signin"))


@teacher_only
@login_required(login_url=reverse_lazy("signin"))
def new_exam(request):
    if request.POST:

        queue = Queue()
        if request.POST.get("switch"):
            queue.set_students(request.POST.getlist('finalQueue'))
            queue.by_students = False
        else:
            queue.set_students([])
            queue.by_students = True
        queue.save()
        print queue

        consultation = Consultation(
            location=request.POST["consultation_location"],
            start_time=request.POST["consultation_start_time"]
        )
        consultation.save()

        exam = Exam(
            teacher=Teacher.objects.get(user=request.user),
            subject=Subject.objects.get(pk=request.POST["subject"]),
            date=request.POST["date"],
            start_time=request.POST["start_time"],
            end_time=request.POST["end_time"],
            students_per_time=request.POST["students_per_time"],
            time_for_student=request.POST["time_for_student"],
            location=request.POST["location"],
            queue=queue,
            consultation=consultation,
        )

        exam.save()

        for material_file in request.FILES.getlist('file'):
            material = Material()
            material.file = material_file
            material.name = str(material_file)
            material.exam = exam
            material.save()

        for group in request.POST.getlist("groups"):
            exam.groups.add(Group.objects.get(pk=group))
        exam.save()
        request.session["last_exam"] = exam.pk
        return HttpResponseRedirect(reverse("exam:details", kwargs={'num': exam.pk}), )
    else:
        teacher = Teacher.objects.get(user=request.user)
        subjects = {}
        for subject in teacher.subject.all():
            subjects[str(subject.pk)] = subject.name

        groups = {}
        for group in teacher.groups.all():
            groups[str(group.pk)] = group.number

        context = {}
        form = UploadMaterialForm()
        context["groups"] = groups
        context["subjects"] = subjects
        context["form"] = form
        return render(request, "exam/new.html", context)


@teacher_only
@login_required(login_url=reverse_lazy("signin"))
def get_group(request, num):
    group = Group.objects.get(pk=num)
    students = Student.objects.filter(group=group)
    result = {}
    for s in students:
        result[str(s.pk)] = s.user.last_name + ' ' + s.user.first_name

    return HttpResponse(json.dumps(result), content_type="application/json")


@login_required(login_url=reverse_lazy("signin"))
def edit_exam(request, num):
    if request.POST:
        exam = Exam.objects.get(pk=num)

        if request.POST.get("switch"):
            exam.queue.set_students(request.POST.getlist('finalQueue'))
            exam.queue.by_students = False
        elif not exam.queue.by_students:
            exam.queue.set_students([])
            exam.queue.by_students = True

        consultation = Consultation.objects.get(pk=exam.consultation.pk)
        consultation.location = request.POST["consultation_location"],
        consultation.start_time = request.POST["consultation_start_time"]

        exam.consultation = consultation

        exam.teacher = Teacher.objects.get(user=request.user)
        exam.subject = Subject.objects.get(pk=request.POST["subject"])
        exam.date = request.POST["date"]
        exam.start_time = request.POST["start_time"]
        exam.end_time = request.POST["end_time"]
        exam.students_per_time = request.POST["students_per_time"]
        exam.time_for_student = request.POST["time_for_student"]
        exam.location = request.POST["location"]

        exam.save()

        for material_file in request.FILES.getlist('file'):
            material = Material()
            material.file = material_file
            material.name = str(material_file)
            material.exam = exam
            material.save()

        exam.groups.remove()
        for group in request.POST.getlist("groups"):
            exam.groups.add(Group.objects.get(pk=group))
        exam.save()
        request.session["last_exam"] = exam.pk
        return HttpResponseRedirect(reverse("exam:details", kwargs={'num': exam.pk}), )
    else:
        exam = Exam.objects.get(pk=num)
        teacher = Teacher.objects.get(user=request.user)
        subjects = {}
        for subject in teacher.subject.all():
            subjects[str(subject.pk)] = subject.name

        selected_groups = []
        for group in exam.groups.all():
            selected_groups.append(str(group.pk))
        groups = {}
        for group in teacher.groups.all():
            groups[str(group.pk)] = group.number

        context = {}
        context["exam"] = exam
        context["selected_groups"] = selected_groups
        context["groups"] = groups
        context["subjects"] = subjects
        return render(request, "exam/edit.html", context)


@login_required(login_url=reverse_lazy("signin"))
def delete_exam(request, num):
    Exam.objects.get(pk=num).delete()
    del request.session["last_exam"]
    return HttpResponseRedirect(reverse("index"))


@login_required(login_url=reverse_lazy("signin"))
def change_password(request):
    if request.POST:
        user = request.user
        context = {}
        if request.POST["new_password"] == request.POST["confirm_new_password"]:
            if request.POST["old_password"] == user.password:
                user.set_password(request.POST["new_password"])
                user.save()
            else:
                context["error"] = "Вы ввели неверный старый пароль"
                return render(request, "exam/change_password.html", context)
        else:
            context["error"] = "Новые пароли не совпадают"
            return render(request, "exam/change_password.html", context)
    else:
        return render(request, "exam/change_password.html")


@login_required(login_url=reverse_lazy("signin"))
def index(request):
    context = {}
    if Student.objects.filter(user=request.user).count() > 0:
        student = Student.objects.get(user=request.user)
        next_exams = Exam.objects.filter(
            Q(date__gte=datetime.now()) & Q(groups__id__exact=student.group.pk) & Q(start=False))
        exams = Exam.objects.filter(groups__id__exact=student.group.pk)
    else:
        teacher = Teacher.objects.get(user=request.user)
        next_exams = Exam.objects.filter(date__gte=datetime.now(), teacher=teacher, start=False)
        exams = Exam.objects.filter(teacher=teacher)
    list = []
    for exam in exams:
        list.append({'pk': exam.pk, 'name': exam.subject.name, 'date': str(exam.date)})
    context["next_exams"] = next_exams
    context["exams"] = json.dumps({'response': list})
    return render(request, "exam/index.html", context)


@login_required(login_url=reverse_lazy("signin"))
def details(request, num):
    context = {}
    if Student.objects.filter(user=request.user).count() > 0:
        context["student"] = Student.objects.get(user=request.user).pk

EExam/templates/exam/about.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>О проекте:</h1>

            <p>
                Вы когда-нибудь:
            <ul>
                <li>сдавали экзамен?</li>
                <li>мучились с расписанием?</li>
                <li>пропускали важные новости?</li>
                <li>искали лекции за день до зачёта?</li>
            </ul>
            </p>
            <p>Мы стараемся решить ежедневные проблемы простого студента</p>
            <img src="{% static "exam/logo.jpg" %}"/><br><br>


            <p><a class="btn btn-primary btn-lg" href="#" role="button">Посмотреть наши проекты</a></p>
        </div>
    </div>

{% endblock %}

EExam/templates/exam/change_password.html
{% extends "base.html" %}

{% block content %}

    <div class="container">

            <div class="row">
                <div class="col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
                    <p class="lead">Смена пороля</p>
                    <form role="form" action="{% url "change_password" %}" method="post">
                        {% if error %}
                            <span class="help-inline text-danger">{{ error }}</span><br><br>
                        {% endif %}
                        <div class="form-group">
                            <input name="old_password" class="form-control" type="password" placeholder="Старый пароль">
                        </div>
                        <div class="form-group">
                            <input name="new_password" class="form-control" type="password" placeholder="Новый пароль">
                        </div>
                        <div class="form-group">
                            <input name="confirm_new_password" class="form-control" type="password" placeholder="Подтвердите новый пароль">
                        </div>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-block">Сохранить</button>
                    </form>
                </div>
            </div>

        </div>

{% endblock %}

EExam/templates/exam/consultation.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <p>Консультация по экзамену "{{ exam.subject.name }}"{% if exam.groups > 1 %} групп {% else %}
                    группы {% endif %}
                    {{ exam.groups.all|join:", " }}</p>

                <p>Время консультации: {{ consultation.start_time }}</p>

                <p>Место проведения консультации: {{ consultation.location }}</p>

                {% if teacher %}
                    <p>Вопросы:</p>
                    {% if questions %}
                        <ol>
                            {% for question in questions %}
                                <li>{{ question.author.user.last_name }}: {{ question.text }}</li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        Вопросов нет
                    {% endif %}
                {% else %}
                    <form action="{% url 'exam:consultation' exam.pk %}" method="post" id="question-form" role="form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="question_text">Вопрос:</label>
                            <textarea name="question_text" class="form-control" id="question_text"
                                      placeholder="Введите текст вопроса."></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        $('form').validate({
            rules: {
                question_text: {
                    maxlength: 255,
                    required: true
                }
            },
            messages: {
                question_text: {
                    maxlength: "Максимальная длина вопроса 255 символов",
                    required: "Вопрос должен быть не пустым"
                }
            },
            errorClass: 'error'
        });
    </script>
{% endblock %}

EExam/templates/exam/details.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <h1>{{ exam.subject.name }}</h1>

        <dl class="dl-horizontal">
            <dt>Предмет:</dt>
            <dd>{{ exam.subject.name }}</dd>

            <dt>Группы:</dt>
            <dd>{{ exam.groups.all|join:", " }}</dd>

            <dt>Дата экзамена:</dt>
            <dd>{{ exam.date }}</dd>

            <dt>Время начала:</dt>
            <dd>{{ exam.start_time }}</dd>

            <dt>Время окончания:</dt>
            <dd>{{ exam.end_time }}</dd>

            <dt>Место проведения экзамена:</dt>
            <dd>{{ exam.location }}</dd>

            <dt>Материалы:</dt>
            <dd>
                <ul class="student-list">
                    {% if materials %}
                        {% for material in materials %}
                            <li><a href="{{ material.file.url }}" download="">{{ material.name }}</a></li>
                        {% endfor %}
                    {% else %}
                        Материалов нет
                    {% endif %}
                </ul>
            </dd>

            <dt>Количество студентов в один прием:</dt>
            <dd>{{ exam.students_per_time }}</dd>

            <dt>Количество минут на одного студента:</dt>
            <dd>{{ exam.time_for_student }}</dd>

            <dt>Очередь:</dt>
            <dd>
                <ol class="student-list">
                    {% if queue %}
                        {% for s in queue %}
                            <li>{{ s }}</li>
                        {% endfor %}
                    {% else %}
                        Очередь пустая
                    {% endif %}
                </ol>
            </dd>
        </dl>


        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-left">
                {% if can_ask or not student %}
                    <button class="btn btn-default"
                            onclick="window.location.href='{% url 'exam:consultation' exam.pk %}'">
                        Консультация
                    </button>
                {% endif %}
                {% if exam.start and student and not finish %}
                    <button class="btn btn-default"
                            onclick="window.location.href='{% url 'reception:student' exam.pk %}'">Посмотреть
                        место в очереди
                    </button>
                {% elif can_start and not exam.start and not student %}
                    <form method="post" action="{% url 'exam:start_exam' exam.id %}" style="display: inline;">
                        {% csrf_token %}
                        <input class="btn btn-primary" type="submit" value="Начать прием"/>
                    </form>
                {% elif exam.start and not finish %}
                    <button class="btn btn-default"
                            onclick="window.location.href='{% url 'reception:teacher' exam.pk %}'">Прием
                    </button>
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-right">
                {% if not student %}
                    <button class="btn btn-primary" onclick="window.location.href='{% url "exam:edit" exam.pk %}'">
                        Редактировать
                    </button>
                    <button class="btn btn-danger" onclick="window.location.href='{% url "exam:delete" exam.pk %}'">
                        Удалить
                    </button>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

EExam/templates/exam/index.html
{% extends "base.html" %}


{% block content %}

    <div class="row">
        <div class="col-xs-12 col-sm-7 col-sm-offset-1 col-md-7 col-md-offset-1 col-lg-7 col-lg-offset-1">
            <div class="calendar">
                <div class="table-responsive">
                    <table unselectable="on" class="table table-bordered">
                        <thead>
                        <tr>
                            <td onclick="prev()"><i class="fa fa-chevron-left"></i></td>
                            <td colspan="5">
                                <span id="year"></span>
                                <span id="month"></span>
                            </td>
                            <td onclick="next()" class="text-right"><i class="fa fa-chevron-right"></i></td>
                        </tr>
                        <tr>
                            <td class="pnm">Пн</td>
                            <td class="pnm">Вт</td>
                            <td class="pnm">Ср</td>
                            <td class="pnm">Чт</td>
                            <td class="pnm">Пт</td>
                            <td class="pnm">Сб</td>
                            <td class="pnm">Вс</td>
                        </tr>
                        </thead>
                        <tbody id="cal">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-3">
            <h4>Предстоящие экзамены</h4>
            <ol>
                {% if next_exams %}
                    {% for exam in next_exams %}
                        <li><a href="{% url 'exam:details' exam.pk %}"> {{ exam.subject.name }} {{ exam.date }} </a>
                        </li>
                    {% endfor %}
                {% else %}
                    <p>В ближайшее время экзаменов не ожидается</p>
                {% endif %}
            </ol>
        </div>
    </div>
    <script>
        Date.prototype['getMonth_'] = Date.prototype['getMonth'];
        Date.prototype['getMonth'] = function () {
            return this.getMonth_() + 1
        };
        var year = new Date().getFullYear();
        var month = new Date().getMonth();
        var months = [
            'Январь',
            'Февраль',
            'Март',
            'Апрель',
            'Май',
            'Июнь',
            'Июль',
            'Август',
            'Сентябрь',
            'Октябрь',
            'Ноябрь',
            'Декабрь'
        ];
        function calRun() {
            var tm = new Date(year, month - 1, 1);
            var day = tm.getDay();
            var start = new Date(tm.getTime() - (1000 * 60 * 60 * 24 * (day - 1)));

            var cal = document.getElementById('cal');

            for (var c = 0; c < 6; c++) {
                var week = document.createElement('tr');
                for (var i = 0; i < 7; i++) {
                    var d = document.createElement('td');
                    var day = new Date(start.getTime() + (1000 * 60 * 60 * 24 * (c * 7 + i)));
                    var html = '';
                    for (var j = 0, l = x.response.length; j < l; j++) {
                        if (new RegExp('^' + x.response[j].date + '$').test(day.getFullYear() + '-' + ((day.getMonth() < 10) ? '0' + (day.getMonth()) : (day.getMonth())) + '-' + ((day.getDate() < 10) ? '0' + day.getDate() : day.getDate()))) {
                            html += '<a href="exam/' + x.response[j].pk + '">' + x.response[j].name + '</a><br />';
                        }
                    }
                    if (html != '') {
                        $(d)
                                .attr('data-container', 'body')
                                .attr('data-toggle', 'popover')
                                .attr('data-placement', 'top')
                                .attr('data-content', html)
                                .popover({html: true})
                                .addClass('exam');
                    }
                    d.innerHTML = day.getDate();
                    if (day.getMonth() != month)
                        d.className = 'pnm';
                    week.appendChild(d);
                }
                cal.appendChild(week);
            }
            document.getElementById('month').innerHTML = months[month - 1];
            document.getElementById('year').innerHTML = year;
        }
        function next() {
            if (month < 12)
                month++;
            else {
                month = 1;
                year++;
            }
            var cal = document.getElementById('cal');
            cal.innerHTML = '';
            calRun();
        }
        function prev() {
            if (month > 1)
                month--;
            else {
                month = 12;
                year--;
            }
            var cal = document.getElementById('cal');
            cal.innerHTML = '';
            calRun();
        }
        a = '{{ exams }}';
        a = a.replace(/&quot;/g, '"')
        console.log(a)
        x = JSON.parse(a)
        console.log(x)
        $(function () {
            $('[data-toggle="popover"]').popover();
        })
        calRun();
    </script>

{% endblock %}

EExam/templates/exam/queue_by_students.html
{% extends "base.html" %}

{% block head %}

    <style>

    </style>

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
            <p class="lead text-center">Название экзамена</p>
            <ol class="student-list">
                {% if queue|length != 0 %}
                    {% for key, value in queue.items %}
                        <li>{{ value }}</li>
                    {% endfor %}
                {% else %}
                    Никого нет в очереди
                {% endif %}
            </ol>
            <form action="{% url 'exam:queue_by_students' exam %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">Занять очередь</button>
            </form>
        </div>
    </div>


{% endblock %}