EExam/EExam/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.core.urlresolvers import reverse, reverse_lazy
from EExam import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^exam/', include('exam.urls', namespace='exam')),
    url(r'^reception/', include('reception.urls', namespace='reception')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^group/(?P<num>[0-9]+)/$', 'exam.views.get_group', name="get_group"),
    url(r'^signin/$', 'exam.views.signin', name="signin"),
    url(r'^about/$', login_required(TemplateView.as_view(template_name="exam/about.html"), login_url=reverse_lazy("signin")), name="about"),
    url(r'^change-password$', 'exam.views.change_password', name="change_password"),
    url(r'^$', 'exam.views.index', name="index"),
    url(r'^signout/$', 'exam.views.signout', name='signout'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

EExam/exam/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import TemplateView

urlpatterns = patterns('exam.views',
    url(r'^(?P<num>[0-9]+)/consultation/$', 'consult', name='consultation'),
    url(r'^new$', 'new_exam', name="new"),
    url(r'^(?P<num>[0-9]+)$', 'details', name="details"),
    url(r'^(?P<num>[0-9]+)/edit$', 'edit_exam', name='edit'),
    url(r'^(?P<num>[0-9]+)/delete', 'delete_exam', name='delete'),
    url(r'^(?P<num>[0-9]+)/queue$', 'queue_by_students', name="queue_by_students"),
    url(r'^(?P<num>[0-9]+)/start$', 'start_exam', name="start_exam")
)

EExam/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" href="{% static "exam/style.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.2.1/css/bootstrap3/bootstrap-switch.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    {% block head %}{% endblock %}

    <script src="{% static "exam/date.js" %}"></script>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.2.1/js/bootstrap-switch.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js"></script>
    <title>E-Exam</title>
</head>
<body>

{% block header %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">E-Exam</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}">Главная</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Экзамены<span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            {% if request.session.teacher %}
                                <li><a href="{% url 'exam:new' %}">Добавить</a></li>
                            {% endif %}
                            {% if request.session.last_exam %}
                                <li><a href="{% url 'exam:details' request.session.last_exam %}">Просмотреть
                                    последний</a></li>
                            {% endif %}
                            <li><a href="{% url 'index' %}">Календарь</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'about' %}">О проекте</a></li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<span
                                    class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'change_password' %}">Сменить пароль</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'signout' %}">Выйти</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>


    </nav>
{% endblock %}

{% block content %}{% endblock %}


{% block footer %}

    <div id="footer" class="text-center" style="height:30px">
        <div class="container">
            <span class="text-muted">E-Exam, 2014</span> <a href="https://github.com/guy-full-in">Автор</a>
        </div>
    </div>
{% endblock %}
<script>
    if ($(window).height() - 30 > $('body').height()) {
        $('#footer').addClass('navbar-fixed-bottom');
    }
</script>
</body>
</html>